name: flutter_platform_control_panel
description: Revolutionary tool for configuration Flutter apps
version: 0.0.2
author: Flutter Platform Team
homepage: https://github.com/mobile-dualbootpartners/flutter-platform-control-panel

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  alice:
    git:
      url: git://github.com/MrtnvM/alice.git
      ref: v0.0.6

  shared_preferences: ">=0.5.3 <1.0.0"
  package_info: 0.4.0+13
  logger: ^0.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
