name: dash_kit_control_panel
description: Revolutionary tool for configuration Flutter apps
version: 1.0.1
homepage: https://github.com/Dash-Kit/dash-kit-control-panel

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  shared_preferences: ^0.5.12
  package_info: ^0.4.3
  logger: ^0.9.4
  device_preview: ^0.4.8
  rxdart: ^0.24.1
  alice_lightweight: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
