name: flutter_platform_control_panel
description: Revolutionary tool for configuration Flutter apps
version: 0.0.1
author: Flutter Platform Team 
homepage:

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  alice:
    git:
      url: git://github.com/MrtnvM/alice.git
      ref: v0.0.5

  shared_preferences: ">=0.5.3 <1.0.0"
  package_info: 0.4.0+6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
